name: Integration Tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install Node dependencies
        run: npm ci
      - name: Start WordPress Environment
        run: npm run wp-env start
      - name: Composer dependencies
        run: composer install
      - name: Run Testsuite
        run: composer run-script tests:integration