name: Plugin Check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer dependencies
        run: composer install --no-dev --no-interaction
      - name: Build
        run:  composer run-script build
      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: './multisite-improvements'